name: CI

on:
  push:
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Muddle
        uses: demonnic/build-with-muddler@v1.4
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: CKMud-Chat.mpackage
          path: build/*.mpackage
